Revert "[RE-PICK] Remove WifiTrackerLib from SettingsLib"
This reverts commit fc269161a57984efa6f857b65292a5d109c00807.

Reason for revert: This breaks build on 6400

packages/apps/Settings/src/com/android/settings/wifi/WifiConnectionPreferenceController.java:40: error: cannot find symbol
import com.android.settingslib.wifi.WifiEntryPreference;
                                   ^
  symbol:   class WifiEntryPreference
  location: package com.android.settingslib.wifi
packages/apps/Settings/src/com/android/settings/wifi/LongPressWifiEntryPreference.java:24: error: cannot find symbol
import com.android.settingslib.wifi.WifiEntryPreference;

Change-Id: Id66d5b8e2363bd1164ba9cfc34489ae67e15099e